Vagrant.configure("2") do |config|
  
  config.vm.box = "generic/rocky9"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end
  config.vm.box_check_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", path: "setup.sh"
end
